In [1]:
import pandas as pd

In [2]:
dfUlta = pd.read_csv ('dfUlta.csv')

In [3]:
dfSephora = pd.read_csv ('dfSephora.csv')

In [4]:
dfUlta

,Unnamed: 0,Brands,Owner,Female,POC,Year Founded,Product Type,Number of Products,Clean Brand
0,0,Ace Beauté,Niye Aniekan-Attang,True,True,2015,NaN,11,False
1,1,ACURE,Jon and Kristy Guerra,True,False,2010,"Skin Care ,Hair ,Bath & Body",46,True
2,2,AG Hair,John and Lotte Davis,True,False,1989,"Hair ,Bath & Body",48,False
3,3,Ahava\t,Ziva Gilad,True,False,1988,"Bath & Body ,Men ,Gifts ,Skin Care",55,False
4,4,Alleyoop,Leila Kashani Manshoory,True,False,2015,"Skin Care ,Bath & Body",4,False
...,...,...,...,...,...,...,...,...,...
551,551,YUNI,Emmanuel Rey,False,False,2015,"Face Mists & Essences ,Face Oils",2,True
552,552,Yves Saint Laurent,Yves Saint Laurent and Pierre Bergé,False,False,1961,"Fragrance ,Men ,Gifts",25,False
553,553,ZitSticka,Daniel Kaplan and Robbie Miller,False,False,2017,"Skin Care ,Bath & Body",10,True
554,554,Zoya,Saad Malik,True,True,1986,"Top & Base Coats ,Nail Care ,Nail Polish",6,False
555,555,18.21 Man Made,"Angel del Solar, Aston LaFon and David del Solar",False,False,2013,"Hair ,Body Care ,Shaving ,Skin Care ,Travel Size",14,False

In [5]:
dfSephora

,Unnamed: 0,Brand Name,Owner,Female,POC,Year Founded,Product Types,Number of Products,Number of Clean,Percent Clean,Clean
0,0,Acqua di Parma,Laura Burdese,True,False,1916,"Fragrance, Bath & Body",37,0,0.00,False
1,1,adwoa beauty,Julian Addo,True,True,2017,Hair,14,13,0.93,True
2,2,AERIN,Aerin Lauder,True,False,2012,Fragrance,19,0,0.00,False
3,3,Algenist,Harrison Dillon and Jonathan Wolfson,False,False,2011,"Skincare,Bath & Body, Makeup",38,0,0.00,False
4,4,Alpha-H,Michelle Doherty,True,False,1995,Skincare,10,0,0.00,False
...,...,...,...,...,...,...,...,...,...,...,...
300,300,Yves Saint Laurent,Yves Saint Laurent and Pierre Bergé,False,False,1961,"Makeup, Skincare, Fragrance, Bath & Body",69,0,0.00,False
301,301,19-69﻿NEW,Johan Bergelin,False,False,2017,Fragrance,14,0,0.00,False
302,302,54 Thrones,Christina Funke Tegbe,True,True,2016,Bath & Body,3,3,1.00,True
303,303,The 7 Virtues,Barb Stegemann,True,False,2010,"Fragrance, Bath & Body",22,21,0.95,True
304,304,8Greens,Dawn Russell,True,False,2014,"Skincare, Bath & Body",2,0,0.00,False

In [6]:
dfUlta.mean()

Unnamed: 0             277.500000
Female                   0.539568
POC                      0.194245
Year Founded          1994.023381
Number of Products      28.503597
Clean Brand              0.174460
dtype: float64

In [7]:
dfSephora.mean()

Unnamed: 0             152.000000
Female                   0.632787
POC                      0.219672
Year Founded          1998.393443
Number of Products      27.940984
Number of Clean          4.518033
Percent Clean            0.267672
Clean                    0.318033
dtype: float64